### ISSUE TITLE
Create export for the user information module

### ISSUE THREAD

**Issue by StefanFCMD** [FraunhoferCESE/madcap-analysis#131]

**Comment by llayman** [comment]
Please report the times in total seconds for export, e.g., instead of Interrupted Time (Month) = 0h 3m 37s, report Interrupted Time (Month) = 217.

Please drop the units (i.e., seconds) from the exported data.

Note that the user information view should still show hour, minute, and second. Only the exports (individual and all users) should covert times to total seconds.
