### ISSUE TITLE
Collection information and Interruption Information don't add up

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap-analysis#139]
![image](https://cloud.githubusercontent.com/assets/1862880/22788929/6a32f244-eeaf-11e6-8103-6a89d6916c72.png)

**Comment by StefanFCMD** [comment]
This is valid behavior. Since an interruption isn't a user's fault, interrupted time is counted into submitted time (now called accountable time). So both together can exceed 24 hours. Moreover, Submitted hours includes a deadzone, which isn't counted into the time (currently 0:00-8:00). Interrupted time doesn't has that deadzone. Therefore, it is also possible to that submitted time is smaller than interrupted time, since interrupted time is counted over a bigger timeframe. Issu can be closed.
